### ISSUE TITLE
checkstyleNoHttp isn't cacheable when builds are run in different locations

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/nohttp#31]
When a build for the same commit is run from two different locations on the file system (as happens when running on CI and then on a developer's machine), the `checkstyleNoHttp` task is not cacheable due to two differences in its inputs. The task's `config.inputProperties` and `configProperties` properties differ. I suspect that this is due to the use of absolute paths when setting up the locations from which configuration should be loaded.

**Comment by rwinch** [comment]
Thanks for the report @wilkinsona Is the use case when using Gradle Enterprice cache (just trying to figure out when this actually occurs)?

I'm thinking this might be related to gh-25. We are using the config_loc:

> Task :checkstyleNohttp
Adding 'config_loc' to checkstyle.configProperties has been deprecated. This is scheduled to be removed in Gradle 6.0. Use checkstyle.configDir instead as this will behave better with up-to-date checks.

There are more details on the issue, but we had not updated because `configDir` was listed as incubating. This got fixed, but now Gradle 6 states that https://docs.gradle.org/6.0/dsl/org.gradle.api.plugins.quality.Checkstyle.html#org.gradle.api.plugins.quality.Checkstyle:configDir[configDir] is deprecated. I'm not sure what we should do here.

I messed around with providing explicit configuration to make the up to date checks work and didn't get very far. Do you think you could provide an explicit configuration nohttp / nohttpCheckstyle that ensure things work as up to date? If we can nail that down, we can try updating the defaults. You could also use the explicit configuration as a workaround in the meantime.

**Comment by facewindu** [comment]
Hi @rwinch 
Using latest master, I tried checking out spring-framework at two locations A and B on my file system.
Running `checkstyleNoHttp` on both, I get this comparison https://ge.spring.io/c/xnrkeemembejw/3ouwptmzq55jm/task-inputs?collapse-all&toggled=WzUyXQ#z56sfccjdrmfu-configproperties
Looking at the problematic input, it contains with
```
checkstyleNohttp {
  doLast {
    println configProperties
  }
}
```
it outputs
```
[nohttp.checkstyle.whitelistFileName:/Users/facewindu/git/forks/tmp/spring-framework/src/nohttp/whitelist.lines, config_loc:/Users/facewindu/git/forks/tmp/spring-framework/src/nohttp]
```
Since the paths are absolute, the relocatability kills caching.
I then changed https://github.com/spring-io/nohttp/blob/d3cacb4a590fb1f7bb657934a055e24fb4f42b49/nohttp-gradle/src/main/java/io/spring/nohttp/gradle/NoHttpCheckstylePlugin.java#L151-L163
to
```
taskMapping.map("configProperties", new Callable<Map<String, Object>>() {
	@Override
	public Map<String, Object> call() throws Exception {
		Map<String, Object> configProperties = new HashMap<>();
		File whitelistFile = extension.getWhitelistFile();
		if (whitelistFile != null) {
			logger.debug("Using whitelist at {}", whitelistFile);
			configProperties.put("nohttp.checkstyle.whitelistFileName", project.relativePath(whitelistFile));
		}
		configProperties.put("config_loc", project.relativePath(getConfigLocation()));
		return configProperties;
	}
});
```
to store relative paths to the project instead of the absolute paths of the whitelist file and the config loc.
This makes some unit tests failing in `NoHttpCheckstylePluginTest` (which check the content of the configProperties).
But after fixing those, all tests are green (including integration tests), and I get a successful cache hit when rerunning from location B, after running a build from location A.
It seems this is enough to fix the task w.r.t caching. Am I missing something in your opinion ?

**Comment by facewindu** [comment]
@rwinch @wilkinsona 
I just submitted a PR (https://github.com/spring-io/nohttp/pull/32) with what I mentioned above. Please take a look.

**Comment by rwinch** [comment]
Closing in favor of gh-32
