### ISSUE TITLE
Replace whitelist with allowlist

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/nohttp#37]
Until recently, I haven’t fully considered the racist connotations of terms like whitelist and blacklist. Better late than never, I hope. While I don’t think the terms have racist origins, the white is good and black is bad implication doesn’t sit comfortably any more.

In nohttp, the whitelist is used for URLs that are allowed to use http or, put another way, that are excluded from https checking. Allow list sounds a bit clumsy to my ears. Perhaps the terms exclusions could be used instead? The documentation can then talk about urls that are excluded from the https requirement and about a default list of exclusions.

**Comment by rwinch** [comment]
Thanks for bringing this up @wilkinsona! I agree this should be changed.

Despite your ears finding allowlist a bit clumsy, I'm inclined to use allowlist. 

I believe that part of the reason it sounds clumsy, is because the industry (world) has used whitelist for so long. To me allowlist is more clear than whitelist. There are other projects (i.e. Rails) using allowlist and I think it is/will be/should be the new norm.

Let me know your thoughts.

**Comment by wilkinsona** [comment]
Thanks, Rob. `allowlist` is fine by me. The meaning is definitely clearer and there’s quite a bit to be said for following Rails’ lead and striving for some consistency in the term that is used as a replacement.

**Comment by blacklistisnotracist** [comment]
I do agree allowlist may be a better term than whitelist because it's more descriptive. That being said, calling blacklist or whitelist a racist word is simply wrong.

First, blacklist's origins have nothing to do with black people. What's more, it has never been used as an abusive word against black people. It's only a certain group of extreme non-black liberals who find the word offensive and try to make them look like it has racist connotations. It's as ridiculous as people who think wearing Chinese clothes is offensive for Chinese people unless they are worn by Chinese people.

Black, as a color, carries negative connotations across many cultures. It's so embedded that hunting down every word from every language is almost impossible and meaningless.

Let's stop calling a group of people black first. Let's start from there. Color comes first, race came later. Colors are tied to images, which can't be changed.

Let's stop the hypocrisy and focus on something that have real impacts.

**Comment by wilkinsona** [comment]
I suspect you haven't read my comment above. It already acknowledges that whitelist and blacklist may not have racist origins, however the implication that white is good and black is bad does not sit comfortably and is something that we need to change.

You've said yourself that "black, as a color, carries negative connotations across many cultures". This, I believe, is something that we need to fix, along with the opposite connotation that white is somehow automatically positive. It may be almost impossible, but that's absolutely no reason not to try.

If we can replace a term with one that is more descriptive while also avoiding reinforcing a white is good, black is bad stereotype, that is undoubtedly a win-win situation.

**Comment by blacklistisnotracist** [comment]
@wilkinsona 

> You've said yourself that "black, as a color, carries negative connotations across many cultures".
This, I believe, is something that we need to fix, along with the opposite connotation that white is somehow automatically positive. It may be almost impossible, but that's absolutely no reason not to try.

Respectfully, this is NOT something we can fix. 

All designers learn [color meaning](http://www.color-wheel-pro.com/color-meaning.html) in design school. This is embedded in many cultures and is reflected in may languages. Humans are normally diurnal creatures and thus fear darkness.

Don't you think it would make more sense if we stop calling black people "black"?

Hunting innocent words down is always a bad idea. Why? Because you will never be able to stop it. If you remember what happened in the world wars. Many governments forced their citizens to stop using words with ancestry from enemies' languages. As a result, people became more and more hostile to each other. "That's an enemy's word, you are a traitor!" But how could you know if a word has its origins in enemy's language? This can go crazy as hell.

I'm not against removing hostile languages. It should be encouraged, of course. But, that should be limited to only when it's more than obvious that the words in interest are hostile or abusive.

Blacklist has never been seen as an abusive word against black people. That's why this is causing a lot of controversies everywhere. Many people actually find it ridiculous to ban the word just because it could potentially hurt some imaginary group of people.

Banning blacklist only contributes to creating a new discriminative word that never existed. Why do we want to do that? If we want to eradicate racism and discrimination, why would we need to create a new discriminative word? It's interesting because most of those who claim blacklist is a racist word are white people.

I'm not opposing a change from blacklist to denylist, or whitelist to allowlist. They are more descriptive for sure. That's a good thing but costs some time. Even if it's a slight trivial change, think about the entire population of developers and their time. If accumulated, it's totally a waste of precious time of everyone.

I'm just saying, don't bring any racist connotations to a word that doesn't actually have any of them. You don't have to mention any racist connotations because that's simply wrong. You could have just said "Blacklist is not descriptive enough. So I'd suggest `denylist` as an alternative." That's it. No mentioning of racist connotations. Please don't twist words' meaning.

**Comment by rwinch** [comment]
I have replaced whitelist with allowlist because it is more meaningful and because allowlist does not have negative/racist connotations. I have left around deprecated methods for whitelist, but they will be removed in an upcoming release.

**Comment by blacklistisnotracist** [comment]
@rwinch Great work. But I still would like to stress out that blacklist or whitelist never had racist connotations.
