### ISSUE TITLE
Support for Gradle 7

### ISSUE THREAD

**Issue by izeye** [spring-io/nohttp#40]
Applying `io.spring.nohttp` plugin with Gradle 7.0-milestone-1 fails as follows:

```
* What went wrong:
A problem was found with the configuration of task ':checkstyleNohttp' (type 'Checkstyle').
  - Directory '/Users/user/IdeaProjects/sample-nohttp/config/nohttp' specified for property 'configDirectory' does not exist.
```

This is a sample project to reproduce it: https://github.com/izeye/sample-nohttp/tree/gradle-wrapper-7.0-milestone-1

Running `./gradlew clean check` reproduces the failure.

**Comment by rwinch** [comment]
Thanks for the report @izeye! Would you be interested in submitting a PR?

**Comment by izeye** [comment]
@rwinch Thanks for asking! I'd like to but don't know much about it.

**Comment by rwinch** [comment]
The changes I pushed ended up breaking the build because they trigger deprecated functionality to be invoked.

The problem is that Gradle now requires getConfiguDirectory() to be used to set the config directory which in turn populates `Checkstyle.properties["config_loc"]`. The problem is that the plugin has historically allowed a `config_loc` that does not exist. This allows defaulting properties in the checkstyle configuration. If the path does not exist, checkstyle just ignores that property (i.e. suppressions configuration).

We can work around this by setting the config_loc property directly, but this triggers deprecation warnings in Gradle.
