### ISSUE TITLE
Unable to instantiate 'NoHttpCheck' class

### ISSUE THREAD

**Issue by AlbertoImpl** [spring-io/nohttp#5]
First, thanks for creating all those tools!
We would like to add some static checks into all our projects to avoid having any reference `http` in our code.

Since `nohttp-gradle` requires gradle 5 and above and some of our projects are still in gradle 4.x we are trying to use `nohttp-checkstyle`.

When adding the module:
```
<module name="Checker">
	<property name="charset" value="UTF-8"/>
	<property name="fileExtensions" value=""/>

	<module name="io.spring.nohttp.checkstyle.check.NoHttpCheck"/>
</module>
```
With a dependency to:
```
 dependencies {
        testRuntimeOnly("io.spring.nohttp:nohttp-checkstyle:0.0.1.BUILD-SNAPSHOT")
}
```
We get the following error when running `gradle check`:
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'io.spring.nohttp.checkstyle.check.NoHttpCheck' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
```
We also tried with copying the source of `NoHttpCheck` into our project and we got the same error.

What are we missing?

Thanks!

**Comment by rwinch** [comment]
Thanks for the report!

It appears that I am able to run with Gradle 4.8+ just fine. Could you provide a sample that reproduces the issue?

**Comment by AlbertoImpl** [comment]
Hi @rwinch, thanks for taking the time to respond!
I reproduced it with a subset of the project I was trying to use:
https://github.com/AlbertoImpl/nohttp-demo

The readme contains the steps I have followed but here are the commits that will showcase that:
- First, creating a basic project with just `checkstyle` using gradle 4
- Second, adding `NoHttp` and returning the specified exception
- Third, upgrading to gradle 5 and having it working

Let me know if you need anything else.

Thanks!

**Comment by rwinch** [comment]
@AlbertoImpl It appears the issue manifests with older versions of Gradle but only if the base plugin is also applied. I pushed out a fix https://github.com/spring-io/nohttp/commit/214602fd5d4eb88cdc75ca372ee010f67d33a59b

Another issue is that Gradle 4.x uses an older version of checkstyle by default. You can update that by providing `checkstyle.toolVersion`. See this commit https://github.com/rwinch/nohttp-demo/commit/8ca8402a5cfe1670b2723eedea4d0ca5b0cee4a5

You should only apply the plugin to the root project. The reason is it searches all files and folders within the project it is applied to. It does this because nohttp must process all files (i.e. including *.gradle files). This is in stark contrast with a typical checkstyle setup which is only checking java source files. You can see the fix here https://github.com/rwinch/nohttp-demo/commit/58f06ce9bc23a77a34095505cc146513518c9a45

You can see the complete sample working at https://github.com/rwinch/nohttp-demo/tree/gh-5

**Comment by AlbertoImpl** [comment]
Thanks a lot Rob,
I confirm that everything works well after applying the changes.

Thanks again for creating these tools!
